# Copyright 2013-2014 by Exploerer Developer.
# made by цвсм<2@GhostBirdOS.org> BeatMicrosoft<BeatMicrosoft@GhostBirdOS.org> Lab Explorer<1@GhostBirdOS.org>
# Explorer makefile
# version:Beta
# 2/14/2015 11:40 PM

CFLAGS = -I "../../include/"

all:
	gcc -c lib.c -o lib.o $(CFLAGS)
	gcc -c task_bar.c -o task_bar.o $(CFLAGS)
	gcc -c window.c -o window.o $(CFLAGS)