# Copyright 2013-2014 by Exploerer Developer.
# made by 米油<2@GhostBirdOS.org> BeatMicrosoft<BeatMicrosoft@GhostBirdOS.org> Lab Explorer<1@GhostBirdOS.org>
# Explorer内核初始化部分makefile
# version:Beta
# 2/14/2015 11:40 PM

CFLAGS = -I "../include/"

all:
	gcc -c main.c -o main.o $(CFLAGS)