# Copyright 2013-2014 by Exploerer Developer.
# made by цвсм<2@GhostBirdOS.org> BeatMicrosoft<BeatMicrosoft@GhostBirdOS.org> Lab Explorer<1@GhostBirdOS.org>
# Explorer fonts makefile
# version:Beta
# 2/14/2015 11:40 PM

CFLAGS = -I "../../include/"

all:
	gcc -c font.c -o font.o $(CFLAGS)
	gcc -c simsun.c -o simsun.o $(CFLAGS)
	gcc -c standard_font.c -o standard_font.o $(CFLAGS)