# Copyright 2013-2014 by Exploerer Developer.
# made by цвсм<2@GhostBirdOS.org> BeatMicrosoft<BeatMicrosoft@GhostBirdOS.org> Lab Explorer<1@GhostBirdOS.org>
# Explorer makefile
# version:Beta
# 2/14/2015 11:40 PM

CFLAGS = -I "../include/"

all:
	gcc -c hdd.c -o hdd.o $(CFLAGS)
	gcc -c i8042.c -o i8042.o $(CFLAGS)
	gcc -c keyboard.c -o keyboard.o $(CFLAGS)
	gcc -c mouse.c -o mouse.o $(CFLAGS)
	gcc -c video.c -o video.o $(CFLAGS)